apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-simple-build-zcav
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-simple-build-zcav
    app.kubernetes.io/part-of: build-suite-test-application-mkuc
  name: test-simple-build-zcav
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: my-nginx
      app.kubernetes.io/instance: test-simple-build-zcav
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-nginx
        app.kubernetes.io/instance: test-simple-build-zcav
    spec:
      containers:
      - image: quay.io/tnevrlka-test/build-e2e-fjmm-tenant/build-suite-test-application-mkuc/test-simple-build-zcav@sha256:9ae02d5cc8e3b49c63024d9e9006939e79db84a7f151462b042bc7089993176e
        name: my-nginx
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
